  fccsw:
    version: [0.5.1]
  fcc-edm:
    version: [0.5.1]
  papas:
    version: [1.2.0]
  podio:
    version: [0.7]
  fcc-physics:
    version: [0.2.1]
  acts-core:
    version: [0.05.02]
  gaudi:
    version: [v28r2]
